# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 18:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField(validators=[tracker.models.validate_zero_to_five])),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Listen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen_date', models.DateField(default=datetime.date.today)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Artist'),
        ),
    ]
