# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20171203_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='listen_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
