# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_album_listen_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
