# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20171203_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='primary_genre',
        ),
        migrations.AddField(
            model_name='album',
            name='primary_genres',
            field=models.ManyToManyField(to='tracker.PrimaryGenre'),
        ),
        migrations.AlterField(
            model_name='primarygenre',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
