# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20171223_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listen',
            options={'ordering': ('-listen_date',)},
        ),
    ]
